root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/api ./cmd/api"
  bin = "./tmp/api"
  full_bin = "./tmp/api"
  include_ext = ["go", "toml"]
  exclude_dir = ["tmp", "bin", "tests"]
  delay = 1000

[log]
  time = false

[misc]
  clean_on_exit = true
